# Other independent functions (e.g. renaming)

rename_data <- function(cats) {
  cats$cats <- ifelse(cats$cats == "Behaviour (e.g. reaction times, accuracy etc.) - non-clinical sample", "Behaviour - non-clinical sample",
                      ifelse(cats$cats == "Behaviour (e.g. reaction times, accuracy etc.) - clinical sample", "Behaviour - clinical sample",
                             ifelse(cats$cats == "Questionnaires - non-clinical sample", "Questionnaires - non-clinical sample",
                                    ifelse(cats$cats == "Questionnaires - clinical sample", "Questionnaires - clinical sample",
                                           ifelse(cats$cats == "Assessment instruments - non-clinical sample", "Assessments - non-clinical sample",
                                                  ifelse(cats$cats == "Assessment instruments - clinical sample", "Assessments - clinical sample",
                                                         ifelse(cats$cats == "Clinical diagnostic data", "Clinical diagnostics",
                                                                ifelse(cats$cats == "Interview transcripts - non-clinical sample", "Interviews - non-clinical sample",
                                                                       ifelse(cats$cats == "Interview transcripts - clinical sample", "Interviews - clinical sample",
                                                                              ifelse(cats$cats == "Structural MRI (sMRI) - non-clinical sample", "sMRI - non-clinical sample",
                                                                                     ifelse(cats$cats == "Structural MRI (sMRI) - clinical sample", "Structural MRI - clinical sample",
                                                                                            ifelse(cats$cats == "Functional MRI (fMRI) - non-clinical sample", "fMRI - non-clinical sample",
                                                                                                   ifelse(cats$cats == "Functional MRI (fMRI) - clinical sample", "fMRI - clinical sample",
                                                                                                          ifelse(cats$cats == "Electroencephalography (EEG) - non-clinical sample", "EEG - non-clinical sample",
                                                                                                                 ifelse(cats$cats == "Electroencephalography (EEG) - clinical sample", "EEG - clinical sample",
                                                                                                                        ifelse(cats$cats == "Magnetic Resonance Spectroscopy (MRS) - non-clinical sample", "MRS - non-clinical sample",
                                                                                                                               ifelse(cats$cats == "Magnetic Resonance Spectroscopy (MRS) - clinical sample", "MRS - clinical sample",
                                                                                                                                      ifelse(cats$cats == "Magnetoencephalography (MEG) - non-clinical sample", "MEG - non-clinical sample",
                                                                                                                                             ifelse(cats$cats == "Magnetoencephalography (MEG) - clinical sample", "MEG - clinical sample",
                                                                                                                                                    ifelse(cats$cats == "Functional Near-infrared Spectroscopy (fNIRS) - non-clinical sample", "fNIRS - non-clinical sample",
                                                                                                                                                           ifelse(cats$cats == "Functional Near-infrared Spectroscopy (fNIRS) - clinical sample", "fNIRS - clinical sample",
                                                                                                                                                                  ifelse(cats$cats == "Diffusion MRI (dMRI) - non-clinical sample", "dMRI - non-clinical sample",
                                                                                                                                                                         ifelse(cats$cats == "Diffusion MRI (dMRI) - clinical sample", "dMRI - clinical sample",
                                                                                                                                                                                ifelse(cats$cats == "Arterial Spin Labelling (ASL) - non-clinical sample", "ASL - non-clinical sample",
                                                                                                                                                                                       ifelse(cats$cats == "Arterial Spin Labelling (ASL) - clinical sample", "ASL - clinical sample",
                                                                                                                                                                                              ifelse(cats$cats == "Eye-tracking - non-clinical sample", "Eye-tracking - non-clinical sample",
                                                                                                                                                                                                     ifelse(cats$cats == "Eye-tracking - clinical sample", "Eye-tracking - clinical sample",
                                                                                                                                                                                                            ifelse(cats$cats == "Pupillometry - non-clinical sample", "Pupillometry - non-clinical sample",
                                                                                                                                                                                                                   ifelse(cats$cats == "Pupillometry - clinical sample", "Pupillometry - clinical sample",
                                                                                                                                                                                                                          ifelse(cats$cats == "Galvanic skin response (GSR) - non-clinical sample", "GSR - non-clinical sample",
                                                                                                                                                                                                                                 ifelse(cats$cats == "Galvanic skin response (GSR) - clinical sample", "GSR - clinical sample",
                                                                                                                                                                                                                                        ifelse(cats$cats == "Gait/walking - non-clinical sample", "Gait - non-clinical sample",
                                                                                                                                                                                                                                               ifelse(cats$cats == "Gait/walking - clinical sample", "Gait - clinical sample",
                                                                                                                                                                                                                                                      ifelse(cats$cats == "Human tissue - non-clinical sample", "Human tissue - non-clinical sample",
                                                                                                                                                                                                                                                             ifelse(cats$cats == "Human tissue - clinical sample", "Human tissue - clinical sample",
                                                                                                                                                                                                                                                                    ifelse(cats$cats == "Kinematic data - non-clinical sample", "Kinematic data - non-clinical sample",
                                                                                                                                                                                                                                                                           ifelse(cats$cats == "Kinematic data - clinical sample", "Kinematic data - clinical sample",
                                                                                                                                                                                                                                                                                  ifelse(cats$cats == "Histological samples - non-clinical sample", "Histological samples - non-clinical sample",
                                                                                                                                                                                                                                                                                         ifelse(cats$cats == "Histological samples - clinical sample", "Histological samples - clinical sample",
                                                                                                                                                                                                                                                                                                ifelse(cats$cats == "Ecological Momentary Assessment (EMA) - non-clinical sample", "EMA - non-clinical sample",
                                                                                                                                                                                                                                                                                                       ifelse(cats$cats == "Ecological Momentary Assessment (EMA) - clinical sample", "EMA - clinical sample",
                                                                                                                                                                                                                                                                                                              ifelse(cats$cats == "Video data - non-clinical sample", "Video data - non-clinical sample",
                                                                                                                                                                                                                                                                                                                     ifelse(cats$cats == "Video data - clinical sample", "Video data - clinical sample",
                                                                                                                                                                                                                                                                                                                            ifelse(cats$cats == "Audio data - non-clinical sample", "Audio data - non-clinical sample",
                                                                                                                                                                                                                                                                                                                                   ifelse(cats$cats == "Audio data - clinical sample", "Audio data - clinical sample",
                                                                                                                                                                                                                                                                                                                                          ifelse(cats$cats == "Simulated data (modelling) - non-clinical sample", "Simulated data - non-clinical sample",
                                                                                                                                                                                                                                                                                                                                                 ifelse(cats$cats == "Simulated data (modelling) - clinical sample", "Simulated data - clinical sample",
                                                                                                                                                                                                                                                                                                                                                        ifelse(cats$cats == "Meta-analytic data extracted from prior literature", "Meta-analytic data",
                                                                                                                                                                                                                                                                                                                                                               as.character(cats$cats)
                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                 )
                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                   )
                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                     )
                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                       )
                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                         )
                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                           )
                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                             )
                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                               )
                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                 )
                                                                                                                                                                                                                          )
                                                                                                                                                                                                                   )
                                                                                                                                                                                                            )
                                                                                                                                                                                                     )
                                                                                                                                                                                              )
                                                                                                                                                                                       )
                                                                                                                                                                                )
                                                                                                                                                                         )
                                                                                                                                                                  )
                                                                                                                                                           )
                                                                                                                                                    )
                                                                                                                                             )
                                                                                                                                      )
                                                                                                                               )
                                                                                                                        )
                                                                                                                 )
                                                                                                          )
                                                                                                   )
                                                                                            )
                                                                                     )
                                                                              )
                                                                       )
                                                                )
                                                         )
                                                  )
                                           )
                                    )
                             )
                      )
  )  
}


is_valid_url <- function(string) {
  pattern <- "(https?|ftp)://[^ /$.?#].[^\\s]*" 
  stringr::str_detect(string, pattern)
}
